#!/bin/sh

# Get absolute path
DIR=$(cd `dirname $0` && pwd)
# echo $DIR

# Link dotfiles
ln -sf $DIR/vimrc $HOME/.vimrc
ln -sf $DIR/i3 $HOME/.config/i3/config
ln -sf $DIR/bashrc $HOME/.bashrc
ln -sf $DIR/bash_profile $HOME/.bash_profile
ln -sf $DIR/inputrc $HOME/.inputrc
ln -sf $DIR/Xresources $HOME/.Xresources
ln -sf $DIR/cache/wal $HOME/.cache/wal
ln -sf $DIR/vscode/snippets $HOME/.config/'Code - OSS'/User/snippets
ln -sf $DIR/vscode/settings.json $HOME/.config/'Code - OSS'/User/settings.json
ln -sf $DIR/bin/ $HOME/bin
