--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/2tb/nasroot/image/wallpaper/pnt_splsh4.jpeg"

-- Special
background="#000000"
foreground="#cfd9d7"
cursor="#cfd9d7"

-- Colors
color0="#000000"
color1="#C75911"
color2="#108773"
color3="#E1A229"
color4="#52708B"
color5="#069C95"
color6="#47BFB9"
color7="#cfd9d7"
color8="#909796"
color9="#C75911"
color10="#108773"
color11="#E1A229"
color12="#52708B"
color13="#069C95"
color14="#47BFB9"
color15="#cfd9d7"
