# Shell variables
# Generated by 'wal'
wallpaper='/mnt/2tb/nasroot/image/wallpaper/pnt_splsh4.jpeg'

# Special
background='#000000'
foreground='#cfd9d7'
cursor='#cfd9d7'

# Colors
color0='#000000'
color1='#C75911'
color2='#108773'
color3='#E1A229'
color4='#52708B'
color5='#069C95'
color6='#47BFB9'
color7='#cfd9d7'
color8='#909796'
color9='#C75911'
color10='#108773'
color11='#E1A229'
color12='#52708B'
color13='#069C95'
color14='#47BFB9'
color15='#cfd9d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
